version: '2'
services:

  web:
    build: 
      context: .
      dockerfile: node.dockerfile
    ports:
      - "4000:4000"
    networks: 
      - todoapp-network
    depends_on:
      - db
    
  db:
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: prentodo
    networks: 
      - todoapp-network

networks: 
  todoapp-network: